"""empty message

Revision ID: 27cad599dda2
Revises: c28d916c3b1c
Create Date: 2019-07-09 15:55:36.798634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27cad599dda2'
down_revision = 'c28d916c3b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('y', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement', 'y')
    # ### end Alembic commands ###
