"""empty message

Revision ID: e23d8677d334
Revises: 27cad599dda2
Create Date: 2019-07-09 15:58:25.040578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23d8677d334'
down_revision = '27cad599dda2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('z', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement', 'z')
    # ### end Alembic commands ###
